version: '3.8'

services:
  # Frontend Service
  frontend:
    image: YOUR_DOCKER_USERNAME/stratos-frontend:latest
    container_name: stratos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend Service
  backend:
    image: YOUR_DOCKER_USERNAME/stratos-backend:latest
    container_name: stratos-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://chinh99078:tranchinh@library.eldw1fw.mongodb.net/
      - JWT_SECRET=your-super-secret-jwt-key-2024
      - GOOGLE_API_KEY=AIzaSyC1gzU8qfoK0gI1foldh3kze8ngymr4XaA
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs

networks:
  app-network:
    driver: bridge
