version: '3.8'

services:
  # Frontend Service
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/stratos-frontend:latest
    container_name: stratos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend Service
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/stratos-backend:latest
    container_name: stratos-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./server/logs:/app/logs

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
